name: Indian Market Portfolio Analysis

on:
  schedule:
    - cron: '0 4 1,15 * *'  # Run on 1st and 15th of every month at 4 AM UTC
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]

jobs:
  portfolio-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

    - name: Create requirements.txt
      run: |
        echo "pandas" >> requirements.txt
        echo "numpy" >> requirements.txt
        echo "yfinance" >> requirements.txt
        echo "networkx" >> requirements.txt
        echo "python-louvain" >> requirements.txt
        echo "scipy" >> requirements.txt
        echo "matplotlib" >> requirements.txt
        echo "requests" >> requirements.txt
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Portfolio Analysis
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python portfolio_analyzer.py
    
    - name: Create Results Directory
      run: mkdir -p results
    
    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: portfolio-analysis-${{ github.run_id }}
        path: results/
        retention-days: 30
    
    - name: Send Failure Notification
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ❌ Portfolio Analysis Failed
          Repository: ${{ github.repository }}
          Workflow: ${{ github.workflow }}
          Run ID: ${{ github.run_id }}
          
    - name: Send Success Notification
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ Portfolio Analysis Completed Successfully
          Repository: ${{ github.repository }}
          Workflow: ${{ github.workflow }}
          Run ID: ${{ github.run_id }}

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run Bandit Security Scan
      run: |
        pip install bandit
        bandit -r . -f custom