name: Indian Market Portfolio Analysis

on:
  schedule:
    - cron: '0 4 1,15 * *'  # Run on 1st and 15th of every month at 4 AM UTC
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]

jobs:
  portfolio-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Increased timeout
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libopenblas-dev

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gdown  # For potential large data downloads

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Run Portfolio Analysis
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        PYTHONUNBUFFERED: 1
      run: |
        mkdir -p results logs
        python portfolio_analyzer.py

    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: portfolio-analysis-${{ github.run_id }}
        path: |
          results/
          logs/
        retention-days: 30

    - name: Commit and Push Results
      run: |
        git add results/ logs/
        git commit -m "Update portfolio analysis results [skip ci]" || echo "No changes to commit"
        git push || echo "No changes to push"

    - name: Send Telegram Notifications
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ${{ job.status == 'success' && '✅' || '❌' }} Portfolio Analysis 
          Status: ${{ job.status }}
          Repository: ${{ github.repository }}
          Run ID: ${{ github.run_id }}