name: Indian Market Analysis Workflow

on:
  schedule:
    # Runs at 2:30 UTC (8:00 AM IST) every 15 days
    - cron: '30 2 1,16 * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  market_analysis:
    # Only run on weekdays
    if: github.event.schedule != null && github.event.schedule == '30 2 1,16 * *' && fromJSON('{"0":"Sunday","1":"Monday","2":"Tuesday","3":"Wednesday","4":"Thursday","5":"Friday","6":"Saturday"}')[format(now(), 'w')] != 'Saturday' && fromJSON('{"0":"Sunday","1":"Monday","2":"Tuesday","3":"Wednesday","4":"Thursday","5":"Friday","6":"Saturday"}')[format(now(), 'w')] != 'Sunday'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy yfinance networkx python-louvain scipy matplotlib requests python-dotenv

    - name: Create results directory
      run: mkdir -p results

    - name: Set up environment variables
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> $GITHUB_ENV
        echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID" >> $GITHUB_ENV

    - name: Run market analysis
      run: python paste.txt

    - name: Upload analysis results
      uses: actions/upload-artifact@v3
      with:
        name: market-analysis-results
        path: results/
        retention-days: 90

    - name: Commit and push to main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout main
        git add results/
        git commit -m "Update market analysis results [skip ci]" || echo "No changes to commit"
        git push origin main || echo "No changes to push"