name: Indian Market Portfolio Analysis

on:
  schedule:
    - cron: '0 4 1,15 * *'  # Run on 1st and 15th of every month at 4 AM UTC
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]

jobs:
  portfolio-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          python3-pip \
          python3-venv

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install additional dependencies
      run: |
        source venv/bin/activate
        pip install \
          scikit-learn \
          python-telegram-bot \
          bandit

    - name: Run Portfolio Analysis
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        source venv/bin/activate
        python portfolio_analyzer.py

    - name: Security Scan with Bandit
      run: |
        source venv/bin/activate
        bandit -r . -f custom

    - name: Create Results Directory
      run: mkdir -p results
    
    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: portfolio-analysis-${{ github.run_id }}-py${{ matrix.python-version }}
        path: results/
        retention-days: 30
    
    - name: Send Failure Notification
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ❌ Portfolio Analysis Failed
          Repository: ${{ github.repository }}
          Workflow: ${{ github.workflow }}
          Python Version: ${{ matrix.python-version }}
          Run ID: ${{ github.run_id }}
          
    - name: Send Success Notification
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ Portfolio Analysis Completed Successfully
          Repository: ${{ github.repository }}
          Workflow: ${{ github.workflow }}
          Python Version: ${{ matrix.python-version }}
          Run ID: ${{ github.run_id }}
