name: Portfolio Analysis

on:
  schedule:
    - cron: '0 0 */15 * *'  # Run every 15 days
  workflow_dispatch:  # Allow manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run portfolio analysis
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python portfolio_analyzer.py
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: portfolio-analysis-results-${{ github.run_id }}
        path: results/
        retention-days: 90
        if-no-files-found: error
        compression-level: 9